version: "3.3"
services:
  builder:
    build: .
    environment:
        MICROPYTHON_LIB: uasyncio
    volumes:
      - ./build.sh:/home/builder/build.sh
      - ./my_module:/home/builder/micropython/ports/esp8266/modules/my_module
      - ./build:/home/builder/build
    entrypoint:
      - bash
      - build.sh


